spring:
  datasource:
    url: jdbc:postgresql://${APPDEPARTURE_DB_HOST:localhost}:${APPDEPARTURE_DB_PORT:5432}/${APPDEPARTURE_DB_NAME:postal}
    username: ${APPDEPARTURE_DB_USERNAME:admin}
    password: ${APPDEPARTURE_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${APPDEPARTURE_DB_SCHEMA_NAME:postal_schema}
  jpa:
    generate-ddl: true
server:
  port: ${APPDEPARTURE_SERVER_PORT:8083}

kafka:
  bootstrap:
    server: ${APPDEPARTURE_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  topic:
    departure:
      compute: ${APPDEPARTURE_KAFKA_DEPARTURE_COMPUTE_TOPIC:departure_duration_compute}
      result: ${APPDEPARTURE_KAFKA_DEPARTURE_RESULT_TOPIC:departure_duration_result}
  group_id: ${APPDEPARTURE_APPNAVIGATION_KAFKA_GROUP_ID:ms_departure}

