spring:
  data:
    mongodb:
      auto-index-creation: ${APPNAVIGATION_AUTO_INDEX_CREATION:true}
      uri: mongodb://${APPNAVIGAION_DB_USERNAME:admin}:${APPNAVIGATION_DB_PASSWORD:admin}@${APPNAVIGATION_DB_HOST:localhost}:${APPNAVIGATION_DB_PORT:27017}/${APPNAVIGATION_DB_NAME:postal}?authSource=${APPNAVIGATION_DB_AUTHSOURCE:admin}&authMechanism=SCRAM-SHA-1
server:
  port: ${APPNAVIGATION_SERVER_PORT:8082}
api:
  directions: ${APPNAVIGATION_DIRECTIONS_API:https://api.mapbox.com/directions/v5/mapbox/driving/}
  geocoding: ${APPNAVIGATION_GEOCODING_API:https://api.mapbox.com/geocoding/v5/mapbox.places/}
  access_token: ${APPNAVIGATION_API_ACCESS_TOKEN}
kafka:
  bootstrap:
    server: ${APPNAVIGATION_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  topic:
    departure:
      compute: ${APPNAVIGATION_KAFKA_DEPARTURE_COMPUTE_TOPIC:departure_duration_compute}
      result: ${APPNAVIGATION_KAFKA_DEPARTURE_RESULT_TOPIC:departure_duration_result}
    user-list:
      request: ${APPNAVIGATION_KAFKA_USER_LIST_REQUEST_TOPIC:user_list_request}
      result: ${APPNAVIGATION_KAFKA_USER_LIST_RESULT_TOPIC:user_list_result}
  group_id: ${APPNAVIGATION_APPNAVIGATION_KAFKA_GROUP_ID:ms_navigaion}
  max_block: ${APPNAVIGATION_KAFKA_MAX_BLOCK:6000}
